/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface StakingContractInterface extends ethers.utils.Interface {
  functions: {
    "addressStakes(address)": FunctionFragment;
    "stake(uint256)": FunctionFragment;
    "viewStakeBalance()": FunctionFragment;
    "viewStakes()": FunctionFragment;
    "withdraw(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addressStakes",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "stake", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "viewStakeBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "viewStakes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addressStakes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "viewStakeBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "viewStakes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "tokenTransfer(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "tokenTransfer"): EventFragment;
}

export type tokenTransferEvent = TypedEvent<
  [string, string, BigNumber] & {
    _from: string;
    _to: string;
    _amount: BigNumber;
  }
>;

export class StakingContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: StakingContractInterface;

  functions: {
    addressStakes(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, boolean] & {
        stakeTime: BigNumber;
        stakedBalance: BigNumber;
        stakeProfit: BigNumber;
        stakeMaturity: boolean;
      }
    >;

    stake(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    viewStakeBalance(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _balance: BigNumber }>;

    viewStakes(
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { _stakes: BigNumber[] }>;

    withdraw(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addressStakes(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, boolean] & {
      stakeTime: BigNumber;
      stakedBalance: BigNumber;
      stakeProfit: BigNumber;
      stakeMaturity: boolean;
    }
  >;

  stake(
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  viewStakeBalance(overrides?: CallOverrides): Promise<BigNumber>;

  viewStakes(overrides?: CallOverrides): Promise<BigNumber[]>;

  withdraw(
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addressStakes(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, boolean] & {
        stakeTime: BigNumber;
        stakedBalance: BigNumber;
        stakeProfit: BigNumber;
        stakeMaturity: boolean;
      }
    >;

    stake(_amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    viewStakeBalance(overrides?: CallOverrides): Promise<BigNumber>;

    viewStakes(overrides?: CallOverrides): Promise<BigNumber[]>;

    withdraw(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "tokenTransfer(address,address,uint256)"(
      _from?: null,
      _to?: null,
      _amount?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { _from: string; _to: string; _amount: BigNumber }
    >;

    tokenTransfer(
      _from?: null,
      _to?: null,
      _amount?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { _from: string; _to: string; _amount: BigNumber }
    >;
  };

  estimateGas: {
    addressStakes(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    stake(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    viewStakeBalance(overrides?: CallOverrides): Promise<BigNumber>;

    viewStakes(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addressStakes(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    stake(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    viewStakeBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    viewStakes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdraw(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
